

#pragma once

#include "parsed_expr.h"
#include <string>
#include <vector>

namespace hybridsearch {

class ColumnExpr : public ParsedExpr {
public:
    explicit ColumnExpr() : ParsedExpr(ParsedExprType::kColumn) {}

    ~ColumnExpr() override;

    [[nodiscard]] std::string ToString() const override;

public:
    std::vector<std::string> names_{};
    bool star_{false};

    // Used to indicate the column expr is generated by unfolding star expr and should be destroyed by BindContext
    // destructor but not parsed syntax tree.
    bool generated_{false};
};

} // namespace hybridsearch
