[general]
version = "0.6.0"
time_zone = "utc-8"
server_mode = "admin"

[network]
server_address = "17.0.0.2"
postgres_port = 5433
http_port = 23821
client_port = 23818
connection_pool_size = 128
peer_ip = "17.0.0.2"
peer_port = 23851
peer_retry_delay = 0
peer_retry_count = 0
peer_connect_timeout = 2000
peer_recv_timeout = 0
peer_send_timeout = 0

[log]
log_filename = "hybridsearch.log"
log_dir = "/var/hybridsearch/leader/log"
log_to_stdout = false
log_file_max_size = "10GB"
log_file_rotate_count = 10
log_level = "trace"

[storage]
persistence_dir = "/var/hybridsearch/leader/persistence"
data_dir = "/var/hybridsearch/leader/data"
optimize_interval = "10s"
cleanup_interval = "60s"
compact_interval = "120s"
mem_index_capacity = 65536
storage_type = "minio"

[storage.object_storage]
url = "17.0.0.1:9005"
bucket_name = "hybridsearch"
access_key = "minioadmin"
secret_key = "minioadmin"
enable_https = false

[buffer]
buffer_manager_size = "4GB"
lru_num = 7
temp_dir = "/var/hybridsearch/leader/tmp"
memindex_memory_quota = "1GB"

[wal]
wal_dir = "/var/hybridsearch/leader/wal"
full_checkpoint_interval = "86400s"
delta_checkpoint_interval = "60s"
wal_compact_threshold = "1GB"
wal_flush = "only_write"

[resource]
resource_dir = "/var/hybridsearch/leader/resource"
