#!/usr/bin/bash

if ! id -u hybridsearch > /dev/null 2>&1 ; then
    useradd --create-home --home-dir /var/hybridsearch --skel /dev/null hybridsearch
fi

mkdir -p /var/hybridsearch && chown -R hybridsearch /var/hybridsearch
