[general]
version                  = "0.6.0"
time_zone                = "utc-8"
server_mode              = "standalone"

[network]
server_address           = "0.0.0.0"

[log]
log_filename             = "hybridsearch.log"
log_dir                  = "/var/hybridsearch/log"
log_to_stdout            = true
log_level               = "trace"

[storage]
persistence_dir          = "/var/hybridsearch/persistence"

storage_type             = "minio"

[storage.object_storage]
url                      = "127.0.0.1:9005"
bucket_name              = "hybridsearch"
access_key               = "minioadmin"
secret_key               = "minioadmin"
enable_https             = false

[buffer]
buffer_manager_size      = "8GB"
temp_dir                 = "/var/hybridsearch/tmp"
result_cache       = "on"

[wal]
wal_dir                  = "/var/hybridsearch/wal"

[resource]
resource_dir             = "/var/hybridsearch/resource"