[general]
version                  = "0.6.0"
time_zone                = "utc-8"

[network]
server_address           = "0.0.0.0"

[log]
log_filename             = "hybridsearch.log"
log_dir                  = "/var/hybridsearch/log"
log_level                = "trace"

[storage]
persistence_dir          = "/var/hybridsearch/persistence"

[buffer]
buffer_manager_size      = "8GB"
temp_dir                 = "/var/hybridsearch/tmp"
result_cache            = "on"

[wal]
wal_dir                  = "/var/hybridsearch/wal"

[resource]
resource_dir             = "/var/hybridsearch/resource"
